# THIS FILE NEEDS MANUAL TYPING, AND THUS FURTHER CHANGE

# ADD BY 1 WHEN THERE IS A BREAKGROUND RELEASE, AFTER WHICH VERSION_MAJOR AND VERSION_MINOR SHOULD BE SET TO 0
VERSION_BREAK=0

# ADD BY 1 WHEN THERE IS A MAJOR RELEASE, AFTER WHICH VERSION_MINOR SHOULD BE SET TO 0
VERSION_MAJOR=1

# ADD BY 1 WHEN THERE IS A MINOR RELEASE
VERSION_MINOR=1

# ADD BY 1 EACH TIME BEFORE YOU COMPILE, IF ANYTHING OF THE GRF HAS BEEN CHANGED 
VERSION_COMPILE=132

# SET TO THE DATE OF COMPILATION (YYYY/MM/DD)
DATE=20240103

# BELOW IS AUTOMATIC
HASH=""
VERSION="${VERSION_COMPILE}"
MODIFIED=".${VERSION_COMPILE}"
TAG="${VERSION_BREAK}.${VERSION_MAJOR}.${VERSION_MINOR}"
DISPLAY_VERSION="${VERSION_BREAK}.${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_COMPILE}"
BRANCH=""

echo "$HASH	$VERSION	$MODIFIED	$TAG	$DISPLAY_VERSION	$BRANCH"