# Define the name and the documentation directory of the NewGRF file.

FILE_NAME       ?= chinasettrains
DOC_FILES       ?= docs/readme.txt docs/changelog.txt
LNG_SCRIPTS     ?= str-csv.py

PYTHON          ?= python

# If you compile GoRender manually, you may replace "renderobject" as "gorender".
GORENDER 	    ?= renderobject --palette "ttd_palette.json" -overwrite
VOX_DIR         ?= gfx/*
